apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      description: The URL of the repository to clone
    - name: branch-name
      type: string
      description: The branch to clone
      default: main
    - name: app-name
      type: string
      description: The name of the application deployment
    - name: build-image
      type: string
      description: The name of the image to build
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)

    - name: lint
      taskRef:
        name: lint
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: args
          value: "-v"

    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
